### ISSUE TITLE
Proposal for 2015 Lightning Talk

### ISSUE THREAD

**Issue by patricknavarromahoney** [austinonrails/members#26]
(Currently added to wiki; Here's the pitch)
We've all heard Pry is great, but 5 minutes will make you a believer. Topics to cover: the top level awesomeness, pry-based powerups (pry-rescue and other such testing/source/documentation integrations, etc), the ease of writing simple debugging plugins, and *most importantly* the pitfalls which are RUBY_VERSION dependent.

**Comment by damon** [comment]
thanks for editing the wiki. No PR needed.
